### ISSUE TITLE
Error while extracting messages

### ISSUE THREAD

**Issue by BorjaJajas** [apenasrr/clonechat#21]
It is a private group and it has restricted forward messages:

 },
    "date": "2023-04-26 10:34:25",
    "chat": {
        "_": "Chat",
        "id": -1001636336293,
        "type": "ChatType.SUPERGROUP",
        "is_verified": false,
        "is_restricted": false,
        "is_creator": false,
        "is_scam": false,
        "is_fake": false,
        "title": "Ourkingdom VIP",
        "photo": {
            "_": "ChatPhoto",
            "small_file_id": "AQADBAAD77gxGx7jCFIAEAIAA1tt0skW____TJvCi13exroABB4E",
            "small_photo_unique_id": "AgAD77gxGx7jCFI",
            "big_file_id": "AQADBAAD77gxGx7jCFIAEAMAA1tt0skW____TJvCi13exroABB4E",
            "big_photo_unique_id": "AgAD77gxGx7jCFI"
        },
        "dc_id": 4,
        "has_protected_content": true,
        "permissions": {
            "_": "ChatPermissions",
            "can_send_messages": false,
            "can_send_media_messages": false,
            "can_send_other_messages": false,
            "can_send_polls": false,
            "can_add_web_page_previews": false,
            "can_change_info": false,
            "can_invite_users": false,
            "can_pin_messages": false
        }
    }
}
Traceback (most recent call last):
  File "C:\Users\Borja\Desktop\clonechat-main\clonechat.py", line 674, in <module>
    main()
  File "C:\Users\Borja\Desktop\clonechat-main\clonechat.py", line 560, in main
    func_sender = get_sender(message)
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Borja\Desktop\clonechat-main\clonechat.py", line 277, in get_sender
    raise Exception
Exception

C:\Users\Borja\Desktop\clonechat-main>cmd /k
C:\Users\Borja\Desktop\clonechat-main>

**Comment by thomassch8861** [comment]
> Hello, I want to run the program every time so that when it arrives a message to the source group it clones it to the destination group, is there any option to do this?

I am running it on my linux vps using tmux
