### ISSUE TITLE
Help, pretty new Not sure what the issue is..

### ISSUE THREAD

**Issue by andykiller86** [apenasrr/clonechat#36]
Pasted the script error Im getting when running the coded?

Enter the number(s) of the file type to clone, separating by comma.
For example, to copy photos and documents type: 1,3
Your answer: 0
New cloning or continuation?
1 = new
2 = resume
Your answer: 1
2/9275 (blank id)
3/9275 (blank id)

Not recognized message type:

{
    "_": "Message",
    "id": 4,
    "from_user": {
        "_": "User",
        "id": 1104838547,
        "is_self": true,
        "is_contact": true,
        "is_mutual_contact": false,
        "is_deleted": false,
        "is_bot": false,
        "is_verified": false,
        "is_restricted": false,
        "is_scam": false,
        "is_fake": false,
        "is_support": false,
        "is_premium": false,
        "first_name": "A",
        "status": "UserStatus.OFFLINE",
        "last_online_date": "2024-02-10 13:32:49",
        "username": "TheSearchEngine",
        "phone_number": "*********"
    },
    "date": "2024-01-04 19:21:05",
    "chat": {
        "_": "Chat",
        "id": -1002072353912,
        "type": "ChatType.SUPERGROUP",
        "is_verified": false,
        "is_restricted": false,
        "is_creator": true,
        "is_scam": false,
        "is_fake": false,
        "title": "TheXxXEngine",
        "username": "TheXxXEngine",
        "photo": {
            "_": "ChatPhoto",
            "small_file_id": "AQADBAADJMAxG-AWuVAAEAIAA4hT1a8W____iRRiN4_CXaIABB4E",
            "small_photo_unique_id": "AgADJMAxG-AWuVA",
            "big_file_id": "AQADBAADJMAxG-AWuVAAEAMAA4hT1a8W____iRRiN4_CXaIABB4E",
            "big_photo_unique_id": "AgADJMAxG-AWuVA"
        },
        "dc_id": 4,
        "has_protected_content": false,
        "permissions": {
            "_": "ChatPermissions",
            "can_send_messages": true,
            "can_send_media_messages": true,
            "can_send_other_messages": true,
            "can_send_polls": false,
            "can_add_web_page_previews": true,
            "can_change_info": false,
            "can_invite_users": true,
            "can_pin_messages": false
        }
    }
}
Traceback (most recent call last):
  File "C:\Users\andy-\Desktop\clonechat-main\clonechat.py", line 674, in <module>
    main()
  File "C:\Users\andy-\Desktop\clonechat-main\clonechat.py", line 560, in main
    func_sender = get_sender(message)
  File "C:\Users\andy-\Desktop\clonechat-main\clonechat.py", line 277, in get_sender
    raise Exception
Exception

**Comment by DevHuney** [comment]
Did you manage to resolve the problem?

**Comment by andykiller86** [comment]
> Did you manage to resolve the problem?

No I didn't, I tried multiple times and still got the same error.

**Comment by timgahmencoding** [comment]
https://github.com/apenasrr/clonechat/issues/37#issuecomment-1986592566
