### ISSUE TITLE
Não consigo clonar um canal

### ISSUE THREAD

**Issue by DevHuney** [apenasrr/clonechat#37]
{
    "_": "Message",
    "id": 2,
    "sender_chat": {
        "_": "Chat",
        "id": -1002124032997,
        "type": "ChatType.CHANNEL",
        "is_verified": false,
        "is_restricted": false,
        "is_creator": false,
        "is_scam": false,
        "is_fake": false,
        "title": "iQuímica 2023",
        "photo": {
            "_": "ChatPhoto",
            "small_file_id": "AQADAQADW60xG8s0EEUAEAIAAxvEwKwW____a6ktj2jpvcYABB4E",
            "small_photo_unique_id": "AgADW60xG8s0EEU",
            "big_file_id": "AQADAQADW60xG8s0EEUAEAMAAxvEwKwW____a6ktj2jpvcYABB4E",
            "big_photo_unique_id": "AgADW60xG8s0EEU"
        },
        "dc_id": 1,
        "has_protected_content": false
    },
    "date": "2024-01-12 21:38:19",
    "chat": {
        "_": "Chat",
        "id": -1002124032997,
        "type": "ChatType.CHANNEL",
        "is_verified": false,
        "is_restricted": false,
        "is_creator": false,
        "is_scam": false,
        "is_fake": false,
        "title": "iQuímica 2023",
        "photo": {
            "_": "ChatPhoto",
            "small_file_id": "AQADAQADW60xG8s0EEUAEAIAAxvEwKwW____a6ktj2jpvcYABB4E",
            "small_photo_unique_id": "AgADW60xG8s0EEU",
            "big_file_id": "AQADAQADW60xG8s0EEUAEAMAAxvEwKwW____a6ktj2jpvcYABB4E",
            "big_photo_unique_id": "AgADW60xG8s0EEU"
        },
        "dc_id": 1,
        "has_protected_content": false
    },
    "mentioned": false,
    "scheduled": false,
    "from_scheduled": false,
    "has_protected_content": false,
    "views": 3582,
    "forwards": 16,
    "outgoing": false
}
Traceback (most recent call last):
  File "C:\Users\huney\OneDrive\Área de Trabalho\clonechat-main\clonechat.py", line 674, in <module>
    main()
  File "C:\Users\huney\OneDrive\Área de Trabalho\clonechat-main\clonechat.py", line 560, in main
    func_sender = get_sender(message)
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huney\OneDrive\Área de Trabalho\clonechat-main\clonechat.py", line 277, in get_sender
    raise Exception
Exception

**Comment by timgahmencoding** [comment]
i never had this error, but maybe try:

line 277: raise Exception
--> change to:
else 
`return foward_video`
