### ISSUE TITLE
'latin-1' codec can't encode characters in position 11-12: ordinal not in range

### ISSUE THREAD

**Issue by despacito008** [apenasrr/clonechat#9]
Traceback (most recent call last):
  File "clonechat.py", line 647, in <module>
    main()
  File "clonechat.py", line 530, in main
    update_cache(CACHE_FILE, list_posted)
  File "clonechat.py", line 395, in update_cache
    with open(CACHE_FILE, mode="w") as file:
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 11-12: ordinal not in range(256)

**Comment by despacito008** [comment]
How to understand this mistake？
